apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/controller.yaml
- manifest/namespace.yaml
- manifest/rbac.yaml
- manifest/route.yaml
- manifest/service.yaml
images:
- digest: sha256:9c8ea9112ed25693df5feb23d42b5384d14a02bc7b0aef54b1742fa2ce5abaf2
  name: ghcr.io/supernetes/controller
