apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/controller.yaml
- manifest/namespace.yaml
- manifest/rbac.yaml
- manifest/route.yaml
- manifest/service.yaml
images:
- digest: sha256:bb616682e538a19f7300e88688298ce5d778132fc6079d4a8bbd770597aa488b
  name: ghcr.io/supernetes/controller
