apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/controller.yaml
- manifest/namespace.yaml
- manifest/rbac.yaml
- manifest/route.yaml
- manifest/service.yaml
images:
- digest: sha256:31bb34002b20db0a6525a5ff27c2bb8b87cc50a1a8fb8f0df1d8cc0046ba2e22
  name: ghcr.io/supernetes/controller
