apiVersion: v1
kind: ServiceAccount
metadata:
  name: supernetes
  namespace: supernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: supernetes
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "secrets", "services"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: supernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supernetes
subjects:
  - kind: ServiceAccount
    name: supernetes
    namespace: supernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-kube-proxy
  namespace: kube-system
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    resourceNames: ["kube-proxy"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-kube-proxy
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-kube-proxy
subjects:
  - kind: ServiceAccount
    name: supernetes
    namespace: supernetes
