apiVersion: v1
kind: ServiceAccount
metadata:
  name: supernetes
  namespace: supernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-kube-proxy
  namespace: kube-system
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    resourceNames: ["kube-proxy"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-kube-proxy
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-kube-proxy
subjects:
  - kind: ServiceAccount
    name: supernetes
    namespace: supernetes
